name: quizme
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  #TODO: Step 1 - Add the rFlutter Alert package as a dependency here and use "Packages get".
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
